#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TOKEN = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
if (!TOKEN) {
  console.error('GITHUB_TOKEN (or GH_TOKEN) is required.');
  process.exit(1);
}

const MARK_START = '<!-- PROJECTS:START -->';
const MARK_END = '<!-- PROJECTS:END -->';

const cfg = yaml.load(readFileSync(resolve(ROOT, 'projects.yml'), 'utf8'));
const minStars = cfg.min_stars ?? 0;

async function fetchRepo(slug) {
  const res = await fetch(`https://api.github.com/repos/${slug}`, {
    headers: {
      Authorization: `Bearer ${TOKEN}`,
      Accept: 'application/vnd.github+json',
      'User-Agent': 'tituskirch-readme-sync'
    }
  });
  if (!res.ok) {
    throw new Error(
      `GitHub API ${res.status} for ${slug}: ${await res.text()}`
    );
  }
  return res.json();
}

const allItems = cfg.categories.flatMap((c) =>
  c.items.map((i) => ({ ...i, category: c.id }))
);

const fetched = await Promise.all(
  allItems.map(async (i) => ({ item: i, data: await fetchRepo(i.repo) }))
);

const missingDescription = fetched.filter(
  ({ data }) => !data.description?.trim()
);

if (missingDescription.length > 0) {
  console.error('The following repos have no GitHub description:');
  for (const { item } of missingDescription) {
    console.error(`  - ${item.repo}`);
    console.error(`    fix: gh repo edit ${item.repo} --description "…"`);
  }
  process.exit(1);
}

const byRepo = new Map(fetched.map(({ item, data }) => [item.repo, data]));

function formatStars(n) {
  if (n < 1000) return `${n}`;
  if (n < 100_000) {
    const v = (Math.floor(n / 100) / 10).toFixed(1).replace(/\.0$/, '');
    return `${v}k+`;
  }
  return `${Math.floor(n / 1000)}k+`;
}

function starLabel(n) {
  const noun = n === 1 ? 'star' : 'stars';
  return `${formatStars(n)} ${noun}`;
}

const lines = [];
for (const cat of cfg.categories) {
  if (cat.items.length === 0) continue;

  lines.push(`### ${cat.title}`, '');
  if (cat.intro) lines.push(cat.intro, '');

  for (const i of cat.items) {
    const d = byRepo.get(i.repo);
    const stars = d.stargazers_count ?? 0;
    const badge = stars >= minStars ? ` (${starLabel(stars)})` : '';
    const icon = i.logo
      ? `<img src="${i.logo}" alt="" width="20" height="20" align="top" />`
      : i.emoji;
    lines.push(
      `- ${icon} **[${d.name}](${d.html_url})**${badge} - ${d.description.trim()}`
    );
  }
  lines.push('');
}

const block = `${MARK_START}\n<!-- generated by scripts/render-readme.mjs from projects.yml — do not edit by hand -->\n\n${lines.join('\n').trimEnd()}\n\n${MARK_END}`;

const readmePath = resolve(ROOT, 'README.md');
const readme = readFileSync(readmePath, 'utf8');
const re = new RegExp(`${MARK_START}[\\s\\S]*?${MARK_END}`);
if (!re.test(readme)) {
  console.error(`README is missing the ${MARK_START} … ${MARK_END} markers.`);
  process.exit(1);
}
const next = readme.replace(re, block);

if (next === readme) {
  console.log('README unchanged.');
} else {
  writeFileSync(readmePath, next);
  console.log('README updated.');
}
